# Самоподписанный сертификат CA
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dev-ca
  namespace: cert-manager
spec:
  isCA: true
  duration: 87600h # 10y
  subject:
    organizations:
      - "Enthusiasts"
    organizationalUnits:
      - "Enthusiasts Lab"
    localities:
      - "Moscow"
    countries:
        - "RU"
  commonName: "Enthusiast home CA shared"
  secretName: dev-ca
  privateKey:
    algorithm: RSA
    encoding: PKCS8
    size: 4096
  issuerRef:
    name: dev-ca-ss
    kind: Issuer
    group: cert-manager.io
