controller:
  ingressClassResource:
    name: system-ingress
    enabled: true
    default: true
    controllerValue: "k8s.io/ingress-nginx"

  replicaCount: 1
  minAvailable: 1
  resources:
    requests:
      cpu: 100m
      memory: 90Mi

  service:
    enabled: true
    type: LoadBalancer

  admissionWebhooks:
    enabled: false
